import "../../components/component.less";
import { ServiceLocator } from "../../utils/serviceLocator";
import { BaseServices } from "../../services/baseServices";
import { registerServices } from "./services";
import { ModsView } from "./ModsView";
import { ModsViewModel } from "./modsViewModel";
import { NewModPackViewModel } from "./newModPackViewModel";
import { ViewLocator } from "../../services/viewLocator";
import { NewModPackView } from "./newModPackView";
import { RenameModPackViewModel } from "./renameModPackViewModel";
import { RenameModPackView } from "./renameModPackView";
import { DeleteModPackViewModel } from "./DeleteModPackViewModel";
import { DeleteModPackView } from "./deleteModPackView";
import { Nav } from "../../shared/nav";
import { INavService } from "../../services/iNavService";
let serviceLocator = new ServiceLocator();
BaseServices.register(serviceLocator);
registerServices(serviceLocator);
let viewLocator = serviceLocator.get(ViewLocator);
viewLocator.registerViewModel(NewModPackViewModel, (vm) => new NewModPackView(vm));
viewLocator.registerViewModel(RenameModPackViewModel, (vm) => new RenameModPackView(vm));
viewLocator.registerViewModel(DeleteModPackViewModel, (vm) => new DeleteModPackView(vm));
let navService = serviceLocator.get(INavService);
let app = document.body;
let nav = navService.buildNav(Nav.pageNames.mods);
let modsView = new ModsView(serviceLocator.get(ModsViewModel));
app.append(nav, modsView.root);
//# sourceMappingURL=modsPage.js.map