// Generated by https://quicktype.io

using System;
using System.Text.Json.Serialization;

namespace FactorioWebInterface.Data.FactorioModPortal
{
    public class ModListResponse
    {
        [JsonPropertyName("results")]
        public Result[] Results { get; set; } = Array.Empty<Result>();
    }

    public class Result
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = "";

        [JsonPropertyName("title")]
        public string? Title { get; set; }

        [JsonPropertyName("owner")]
        public string? Owner { get; set; }

        [JsonPropertyName("summary")]
        public string? Summary { get; set; }

        [JsonPropertyName("downloads_count")]
        public long DownloadsCount { get; set; }

        [JsonPropertyName("category")]
        public string? Category { get; set; }

        [JsonPropertyName("score")]
        public double Score { get; set; }

        [JsonPropertyName("releases")]
        public Release[] Releases { get; set; } = Array.Empty<Release>();

        [JsonPropertyName("thumbnail")]
        public string? Thumbnail { get; set; }
    }

    public class Release
    {
        [JsonPropertyName("download_url")]
        public string? DownloadUrl { get; set; }

        [JsonPropertyName("file_name")]
        public string? FileName { get; set; }

        [JsonPropertyName("info_json")]
        public InfoJson? InfoJson { get; set; }

        [JsonPropertyName("released_at")]
        public DateTimeOffset ReleasedAt { get; set; }

        [JsonPropertyName("version")]
        public string? Version { get; set; }

        [JsonPropertyName("sha1")]
        public string? Sha1 { get; set; }
    }

    public class InfoJson
    {
        [JsonPropertyName("factorio_version")]
        public string? FactorioVersion { get; set; }
    }
}
